---
- name: Install default packages to Debian systems
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - iotop
    - htop
    - mc
    - net-tools
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg-agent

- name: Install pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes
